# Generated by Django 5.2.9 on 2025-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='lab_test_status',
            field=models.CharField(choices=[('PENDING', 'Lab Test Pending'), ('PASS', 'Test Passed'), ('FAIL', 'Test Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active in Inventory'), ('TRANSIT', 'In Transit'), ('ARCHIVED', 'Archived/Sold'), ('Disposed', 'Disposed/Destroyed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='storage_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('HARVEST', 'Harvested Raw Material'), ('PROCESSED', 'Processed Product'), ('FINAL', 'Final Consumer Product')], default='HARVEST', max_length=20),
        ),
    ]
