# Generated by Django 5.2.9 on 2025-12-05 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('unit_type', models.CharField(choices=[('HARVEST', 'Harvested Raw Material'), ('PROCESSED', 'Processed Product')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_units', to='inventory.organization')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_units', to='inventory.unit')),
            ],
        ),
    ]
