# Generated by Django 4.2.16 on 2025-12-08 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_unit_description_unit_lab_test_status_unit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(default='No Email Address', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='licence_number',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active in Inventory'), ('TRANSIT', 'In Transit'), ('ARCHIVED', 'Archived/Sold'), ('DISPOSED', 'Disposed/Destroyed')], default='ACTIVE', max_length=20),
        ),
    ]
